version: '3'

services:
    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile.prod
      container_name: symfony-docker-frontend
      command: serve -s build -l 3000
      restart: unless-stopped
      networks:
        - symfony-network

    api:
      build: ./api
      container_name: symfony-docker-api
      command: npm run start
      restart: unless-stopped
      environment:
        - PORT=3001
        - MONGO_URL=mongodb://api_db:27017/api
        - AUTH_API_URL=http://auth:3002/api
      depends_on:
        - api_db
      networks:
        - symfony-network

    auth:
      build: ./auth
      container_name: symfony-docker-auth
      command: npm run start
      restart: unless-stopped
      environment:
        - PORT=3002
        - MONGO_URL=mongodb://auth_db:27017/auth
        - API_URL=http://api:3001/api
      depends_on:
        - auth_db
      networks:
        - symfony-network

    api_db:
      image: mongo:latest
      container_name: symfony-docker-api-db
      volumes:
      - mongodb_api:/data/db
      networks:
        - symfony-network


    auth_db:
      image: mongo:latest
      container_name: symfony-docker-auth-db
      volumes:
        - mongodb_auth:/data/db
      networks:
        - symfony-network


    nginx:
      image: nginx:stable-alpine
      container_name: symfony-docker-nginx
      ports:
        - "80:80"
      volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
      depends_on:
        - frontend
        - api
        - auth
      networks:
        - symfony-network
volumes:
  mongodb_api:
  mongodb_auth:

networks:
  symfony-network:
    driver: bridge



